
version: 1
models:

  - name: item
    description: "Properties for all items available on the Grand Exchange."
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: name
        description: "Item name"
        data_tests:
          - unique
          - not_null
      - name: description
        description: "The item's examine text."
        data_tests:
          - not_null
      - name: volume
        description: "The total number of this item that may be traded across the entire game economy in a day."
        data_tests:
          - not_null
      - name: limit
        quote: true  # limit is an SQL keyword
        description: "The individual 4-hour buying limit for any one player."
        data_tests:
          - not_null
      - name: value
        description: "The in-game value modifier, used to determine alchemy values and the price to keep items on death."
        data_tests:
          - not_null
      - name: high_alch
        description: "The amount of gold generated from casting high alchemy on the item."
      - name: low_alch
        description: "The amount of gold gained from casting low alchemy on the item."
      - name: icon
        description: "URL to the item's icon."
        data_tests:
          - not_null
      - name: icon_large
        description: "URL to the item's large icon."
        data_tests:
          - not_null
      - name: type
        description: "The item's category."
        data_tests:
          - not_null
      - name: type_icon
        description: "URL to the item's category icon."
        data_tests:
          - not_null

  - name: exchange_history
    description: "Daily aggregates for prices, trade volume, etc. per item."
    columns:
      - name: id
        description: The item id.
        data_tests:
          - not_null
      - name: price
        description: The average daily price of the item.
        data_tests:
          - not_null
      - name: timestamp
        description: The date and time of the record.
        data_tests:
          - not_null
      - name: volume
        description: The total volume traded, where available.
        data_tests:
          - not_null

  - name: active_players_weekly
    description: "Count of active players each week."
    columns:
      - name: date
        description: "The first day of the given week."
        data_tests:
          - not_null
      - name: rs3_count
        description: "The count of active RS3 players."
        data_tests:
          - not_null
      - name: osrs_count
        description: "The count of active OSRS players."
        data_tests:
          - not_null
      - name: total_count
        description: "The count of active RS3 and OSRS players."
        data_tests:
          - not_null
      
  - name: event
    description: "Significant event in RuneScape history."
    columns:
      - name: date
        quote: true
        description: "The date of the event."
      - name: game
        description: "The game the event happened for."
      - name: description
        description: "A description of the event."
